In [16]:
import numpy as np
import operator

In [2]:
a = np.matrix([[1,2,3],[2,3,4],[3,4,5]]);a

matrix([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [3]:
a.sum(0)

matrix([[ 6,  9, 12]])

In [4]:
a.sum(1)

matrix([[ 6],
        [ 9],
        [12]])

In [8]:
vetoLable = {}
vetoLable['a'] = vetoLable.get('a',0) + 1

In [9]:
vetoLable

{'a': 1}

In [10]:
vetoLable['b'] = 2
vetoLable['c'] = 3

In [13]:
vetoLable

{'a': 1, 'b': 2, 'c': 3}

In [18]:
result = sorted(vetoLable.items(),key=operator.itemgetter(1),reverse = True)

In [19]:
result[0]

('c', 3)

In [20]:
result[0][0]

'c'

In [21]:
result

[('c', 3), ('b', 2), ('a', 1)]

In [22]:
type(result)

list